namespace SpriteKind {
    export const BOSS = SpriteKind.create()
    export const heroshot = SpriteKind.create()
}
controller.combos.attachCombo("", function () {
    new_variable = sprites.createProjectileFromSprite(img`
        . . . . . . . b b . . . . . . . 
        . . . . . . b c c b . . . . . . 
        . . . . . b c c c c b . . . . . 
        . . . . b c c c c c c b . . . . 
        . . . . b c c c c c c b . . . . 
        . . . . b c c c c c c b . . . . 
        . . . . b c c c c c c b . . . . 
        . . . . . b c c c c a . . . . . 
        . . . . . b a c c c b . . . . . 
        . . . . . . a c c a b . . . . . 
        . . . . . . b a c b . . . . . . 
        . . . . . . b a c b . . . . . . 
        . . . . . . . a c a . . . . . . 
        . . . . . . . a c a . . . . . . 
        . . . . . . . a c a . . . . . . 
        . . . . . . . a c a . . . . . . 
        `, mySprite, 0, -200)
    new_variable.setKind(SpriteKind.heroshot)
})
controller.combos.attachCombo("U+A", function () {
    scaling.scaleByPixels(mySprite, 10, ScaleDirection.Uniformly, ScaleAnchor.Middle)
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f f 2 f e f . . 
        . . f f f 2 f e e 2 2 f f f . . 
        . . f e 2 f f e e 2 f e e f . . 
        . f f e f f e e e f e e e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . . e f f f f f f f f 4 e . . 
        . . . 4 f 2 2 2 2 2 e d d 4 . . 
        . . . e f f f f f f e e 4 . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e f 2 f f f 2 f 2 e f . . 
        . . f f f 2 2 e e f 2 f f f . . 
        . . f e e f 2 e e f f 2 e f . . 
        . f f e e e f e e e f f e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f e . . . 
        . . 4 d d e 2 2 2 2 2 f 4 . . . 
        . . . 4 e e f f f f f f e . . . 
        . . . . . . . . . f f f . . . . 
        `],
    500,
    true
    )
    mySprite2 = 0
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ............ffff..............
        ..........fff22fff............
        .........fff2222fff...........
        ........fffeeeeeefff..........
        ........ffe222222eef..........
        ........fe2ffffff2ef......89..
        ........ffffeeeeffff.....ed8..
        .......ffefbf44fbfeff...ede...
        .......fee41fddf14eef..ede....
        ........feeddddddeef..ede.....
        .........fee4444eef..ede......
        .......4e4f222222f4e4de.......
        .......4eef222222fee4e........
        .......444f445544f444.........
        ...........ffffff.............
        ...........ff..ff.............
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ............ffff..............
        ..........fff22fff............
        .........fff2222fff...........
        ........fffeeeeeefff..........
        ........ffe222222eef.......89.
        ........fe2ffffff2ef........8.
        ........ffffeeeeffff.....ed...
        .......ffefbf44fbfeff...ede...
        .......fee41fddf14eef..ede....
        ........feeddddddeef..ede.....
        .........fee4444eef..ede......
        .......4e4f222222f4e4de.......
        .......4eef222222fee4e........
        .......444f445544f444.........
        ...........ffffff.............
        ...........ff..ff.............
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ............ffff..............
        ..........fff22fff............
        .........fff2222fff...........
        ........fffeeeeeefff........89
        ........ffe222222eef.........8
        ........fe2ffffff2ef..........
        ........ffffeeeeffff.....ed...
        .......ffefbf44fbfeff...ede...
        .......fee41fddf14eef..ede....
        ........feeddddddeef..ede.....
        .........fee4444eef..ede......
        .......4e4f222222f4e4de.......
        .......4eef222222fee4e........
        .......444f445544f444.........
        ...........ffffff.............
        ...........ff..ff.............
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ............ffff..............
        ..........fff22fff............
        .........fff2222fff...........
        ........fffeeeeeefff..........
        ........ffe222222eef..........
        ........fe2ffffff2ef..........
        ........ffffeeeeffff.....ed...
        .......ffefbf44fbfeff...ede...
        .......fee41fddf14eef..ede...9
        ........feeddddddeef..ede....9
        .........fee4444eef..ede.....9
        .......4e4f222222f4e4de......9
        .......4eef222222fee4e.......9
        .......444f445544f444........9
        ...........ffffff............9
        ...........ff..ff............9
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ............ffff..............
        ..........fff22fff............
        .........fff2222fff...........
        ........fffeeeeeefff..........
        ........ffe222222eef.......9..
        ........fe2ffffff2ef........9.
        ........ffffeeeeffff.....ed..9
        .......ffefbf44fbfeff...ede..9
        .......fee41fddf14eef..ede...9
        ........feeddddddeef..ede....9
        .........fee4444eef..ede.....9
        .......4e4f222222f4e4de......9
        .......4eef222222fee4e.......9
        .......444f445544f444........9
        ...........ffffff............9
        ...........ff..ff............9
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ............ffff..............
        ..........fff22fff......9.....
        .........fff2222fff......9....
        ........fffeeeeeefff......9...
        ........ffe222222eef.......9..
        ........fe2ffffff2ef........9.
        ........ffffeeeeffff.....ed..9
        .......ffefbf44fbfeff...ede..9
        .......fee41fddf14eef..ede...9
        ........feeddddddeef..ede....9
        .........fee4444eef..ede.....9
        .......4e4f222222f4e4de......9
        .......4eef222222fee4e.......9
        .......444f445544f444........9
        ...........ffffff............9
        ...........ff..ff............9
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ....................9.........
        .....................9........
        ......................9.......
        ............ffff.......9......
        ..........fff22fff......9.....
        .........fff2222fff......9....
        ........fffeeeeeefff......9...
        ........ffe222222eef.......9..
        ........fe2ffffff2ef........9.
        ........ffffeeeeffff.....ed..9
        .......ffefbf44fbfeff...ede..9
        .......fee41fddf14eef..ede...9
        ........feeddddddeef..ede....9
        .........fee4444eef..ede.....9
        .......4e4f222222f4e4de......9
        .......4eef222222fee4e.......9
        .......444f445544f444........9
        ...........ffffff............9
        ...........ff..ff............9
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        .........88888888888..........
        ........8999999999998.........
        .........8888888888898........
        ....................898.......
        .....................898......
        ............ffff......898.....
        ..........fff22fff.....898....
        .........fff2222fff.....898...
        ........fffeeeeeefff.....898..
        ........ffe222222eef......898.
        ........fe2ffffff2ef.......898
        ........ffffeeeeffff.....ed.89
        .......ffefbf44fbfeff...ede.89
        .......fee41fddf14eef..ede..89
        ........feeddddddeef..ede...89
        .........fee4444eef..ede....89
        .......4e4f222222f4e4de.....89
        .......4eef222222fee4e......89
        .......444f445544f444.......89
        ...........ffffff...........89
        ...........ff..ff...........89
        `],
    100,
    false
    )
    mySprite2 = 2
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        ....ffffff...............
        ..ffeeeef2f..............
        .ffeeeef222f.............
        .feeeffeeeef.............
        .ffffee2222ef............
        .fe222ffffe2fff..........
        fffffffeeeffeef..........
        ffe44ebf44fedef..........
        fee4d41fdfedef...........
        .feee4ddfedef............
        ..ffee4fedef.............
        ...4ddfedef..............
        ...eddedeff..............
        ...f55f4f5f..............
        ....ffffff...............
        .....fff.................
        `,img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        ...................2.....
        ....ffffff........252....
        ..ffeeeef2f......242.....
        .ffeeeef222f....252......
        .feeeffeeeef...242.......
        .ffffee2222ef.252........
        .fe222ffffe2fff2.........
        fffffffeeeffeef..........
        ffe44ebf44fedef..........
        fee4d41fdfedef...........
        .feee4ddfedef............
        ..ffee4fedef.............
        ...4ddfedef..............
        ...eddedeff..............
        ...f55f4f5f..............
        ....ffffff...............
        .....fff.................
        `,img`
        .........................
        .........................
        .........................
        .........................
        .........................
        ......................2..
        .....................242.
        ....................242..
        ...................242...
        ....ffffff...4....242....
        ..ffeeeef2f....4.242.....
        .ffeeeef222f......2......
        .feeeffeeeef....4........
        .ffffee2222ef.....4......
        .fe222ffffe2fff..........
        fffffffeeeffeef....4.....
        ffe44ebf44fedef..........
        fee4d41fdfedef...........
        .feee4ddfedef............
        ..ffee4fedef.............
        ...4ddfedef..............
        ...eddedeff..............
        ...f55f4f5f..............
        ....ffffff...............
        .....fff.................
        `,img`
        .........................
        .........................
        .........................
        .........................
        .......................2.
        ......................242
        .....................242.
        ....................242..
        ..............4....242...
        ....ffffff......4.242....
        ..ffeeeef2f........2.....
        .ffeeeef222f.....4.......
        .feeeffeeeef.......4.....
        .ffffee2222ef............
        .fe222ffffe2fff.....4....
        fffffffeeeffeef..........
        ffe44ebf44fedef..........
        fee4d41fdfedef...........
        .feee4ddfedef............
        ..ffee4fedef.............
        ...4ddfedef..............
        ...eddedeff..............
        ...f55f4f5f..............
        ....ffffff...............
        .....fff.................
        `,img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        ..................22.....
        ..................22.....
        ....ffffff...............
        ..ffeeeef2f..............
        .ffeeeef222f.............
        .feeeffeeeef.............
        .ffffee2222ef............
        .fe222ffffe2fff..........
        fffffffeeeffeef..........
        ffe44ebf44fedef..........
        fee4d41fdfedef...........
        .feee4ddfedef............
        ..ffee4fedef.............
        ...4ddfedef..............
        ...eddedeff..............
        ...f55f4f5f..............
        ....ffffff...............
        .....fff.................
        `,img`
        .........................
        .........................
        .........................
        .........................
        ...............2.......2.
        .........................
        .................2..2....
        ..................22.....
        ..................22.....
        ....ffffff.......2..2....
        ..ffeeeef2f..............
        .ffeeeef222f...2.......2.
        .feeeffeeeef.............
        .ffffee2222ef............
        .fe222ffffe2fff..........
        fffffffeeeffeef..........
        ffe44ebf44fedef..........
        fee4d41fdfedef...........
        .feee4ddfedef............
        ..ffee4fedef.............
        ...4ddfedef..............
        ...eddedeff..............
        ...f55f4f5f..............
        ....ffffff...............
        .....fff.................
        `,img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .....ffff................
        ...fff22fff..............
        ..fff2222fff.............
        .fffeeeeeefff............
        .ffe222222eef............
        .fe2ffffff2ef............
        .ffffeeeeffff.....ed.....
        ffefbf44fbfeff...ede.....
        fee41fddf14eef..ede......
        .feeddddddeef..ede.......
        ..fee4444eef..ede........
        4e4f222222f4e4de.........
        4eef222222fee4e..........
        444f445544f444...........
        ....ffffff...............
        ....ff..ff...............
        `],
    50,
    false
    )
    mySprite2 = 1
    music.magicWand.play()
})
sprites.onOverlap(SpriteKind.heroshot, SpriteKind.BOSS, function (sprite, otherSprite) {
    statusbar2.value += -5
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d e e e e e f . . . 
        . . . f e 4 e d d 4 f . . . . . 
        . . . f 2 2 e d d e f . . . . . 
        . . f f 5 5 f e e f f f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `,img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e d d 4 . . . . 
        . . . f 2 2 2 2 e d d e . . . . 
        . . f f 5 5 4 4 f e e f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `],
    500,
    true
    )
    mySprite2 = 0
})
statusbars.onZero(StatusBarKind.Health, function (status) {
    game.over(false)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e e e d d d f . . . 
        . . . . . f 4 d d e 4 e f . . . 
        . . . . . f e d d e 2 2 f . . . 
        . . . . f f f e e f 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `,img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . 4 d d e 4 4 4 e f . . . 
        . . . . e d d e 2 2 2 2 f . . . 
        . . . . f e e f 4 4 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `],
    500,
    true
    )
    mySprite2 = 0
})
controller.combos.attachCombo("D+A", function () {
    scaling.scaleByPixels(mySprite, -1, ScaleDirection.Uniformly, ScaleAnchor.Middle)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . . f e 4 d d d d 4 e f e . . 
        . . f e f 2 2 2 2 e d d 4 e . . 
        . . e 4 f 2 2 2 2 e d d e . . . 
        . . . . f 4 4 5 5 f e e . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f e e 2 2 2 2 2 2 e f f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . e f e 4 d d d d 4 e f . . . 
        . . e 4 d d e 2 2 2 2 f e f . . 
        . . . e d d e 2 2 2 2 f 4 e . . 
        . . . . e e f 5 5 4 4 f . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . . . . . . f f f . . . . 
        `],
    500,
    true
    )
    mySprite2 = 0
})
controller.combos.attachCombo("A+B", function () {
	
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (mySprite2 == 1) {
        otherSprite.destroy()
    }
})
sprites.onOverlap(SpriteKind.BOSS, SpriteKind.Player, function (sprite, otherSprite) {
    if (mySprite2 == 2) {
        music.jumpDown.play()
    } else {
        statusbar.value += -50
    }
})
let projectile2: Sprite = null
let projectile: Sprite = null
let new_variable: Sprite = null
let mySprite2 = 0
let mySprite: Sprite = null
let statusbar2: StatusBarSprite = null
let statusbar: StatusBarSprite = null
statusbar = statusbars.create(20, 4, StatusBarKind.Health)
statusbar2 = statusbars.create(50, 5, StatusBarKind.EnemyHealth)
let mySprite3 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.BOSS)
statusbar2.max = 10000
statusbar2.value = 10000
statusbar2.setBarBorder(1, 15)
statusbar2.attachToSprite(mySprite3)
scaling.scaleByPixels(mySprite3, 30, ScaleDirection.Uniformly, ScaleAnchor.Middle)
mySprite = sprites.create(img`
    .....ffff...........
    ...fff22fff.........
    ..fff2222fff........
    .fffeeeeeefff.......
    .ffe222222eef.......
    .fe2ffffff2ef.......
    .ffffeeeeffff.....ed
    ffefbf44fbfeff...ede
    fee41fddf14eef..ede.
    .feeddddddeef..ede..
    ..fee4444eef..ede...
    4e4f222222f4e4de....
    4eef222222fee4e.....
    444f445544f444......
    ....ffffff..........
    ....ff..ff..........
    `, SpriteKind.Player)
statusbar.attachToSprite(mySprite)
statusbar.setBarBorder(1, 15)
mySprite2 = 0
controller.moveSprite(mySprite)
tiles.setCurrentTilemap(tilemap`level1`)
scene.cameraFollowSprite(mySprite)
tiles.placeOnTile(mySprite, tiles.getTileLocation(6, 8))
game.onUpdateInterval(5000, function () {
	
})
game.onUpdateInterval(5000, function () {
    mySprite3.follow(mySprite, 50)
    projectile = sprites.createProjectileFromSprite(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........a...............
        ........aba..............
        ........aba..............
        .......aaba..............
        .......aaba..............
        .......abbaa.............
        ......aabfba.............
        ......abffba.............
        .....abfccfba............
        .....abfccfba............
        .....abfccfba............
        .....abffffba............
        ......abbbba.............
        .......aaaa..............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `, mySprite3, 50, 50)
    projectile2 = sprites.createProjectileFromSprite(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........a...............
        ........aba..............
        ........aba..............
        .......aaba..............
        .......aaba..............
        .......abbaa.............
        ......aabfba.............
        ......abffba.............
        .....abfccfba............
        .....abfccfba............
        .....abfccfba............
        .....abffffba............
        ......abbbba.............
        .......aaaa..............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `, mySprite3, 0, 50)
    projectile2 = sprites.createProjectileFromSprite(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........a...............
        ........aba..............
        ........aba..............
        .......aaba..............
        .......aaba..............
        .......abbaa.............
        ......aabfba.............
        ......abffba.............
        .....abfccfba............
        .....abfccfba............
        .....abfccfba............
        .....abffffba............
        ......abbbba.............
        .......aaaa..............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `, mySprite3, 50, 50)
    projectile2 = sprites.createProjectileFromSprite(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........a...............
        ........aba..............
        ........aba..............
        .......aaba..............
        .......aaba..............
        .......abbaa.............
        ......aabfba.............
        ......abffba.............
        .....abfccfba............
        .....abfccfba............
        .....abfccfba............
        .....abffffba............
        ......abbbba.............
        .......aaaa..............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `, mySprite3, 25, 25)
    projectile2 = sprites.createProjectileFromSprite(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........a...............
        ........aba..............
        ........aba..............
        .......aaba..............
        .......aaba..............
        .......abbaa.............
        ......aabfba.............
        ......abffba.............
        .....abfccfba............
        .....abfccfba............
        .....abfccfba............
        .....abffffba............
        ......abbbba.............
        .......aaaa..............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `, mySprite3, -25, 25)
    projectile2 = sprites.createProjectileFromSprite(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........a...............
        ........aba..............
        ........aba..............
        .......aaba..............
        .......aaba..............
        .......abbaa.............
        ......aabfba.............
        ......abffba.............
        .....abfccfba............
        .....abfccfba............
        .....abfccfba............
        .....abffffba............
        ......abbbba.............
        .......aaaa..............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `, mySprite3, 50, 50)
    projectile2 = sprites.createProjectileFromSprite(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........a...............
        ........aba..............
        ........aba..............
        .......aaba..............
        .......aaba..............
        .......abbaa.............
        ......aabfba.............
        ......abffba.............
        .....abfccfba............
        .....abfccfba............
        .....abfccfba............
        .....abffffba............
        ......abbbba.............
        .......aaaa..............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `, mySprite3, -12, 12)
    projectile2 = sprites.createProjectileFromSprite(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........a...............
        ........aba..............
        ........aba..............
        .......aaba..............
        .......aaba..............
        .......abbaa.............
        ......aabfba.............
        ......abffba.............
        .....abfccfba............
        .....abfccfba............
        .....abfccfba............
        .....abffffba............
        ......abbbba.............
        .......aaaa..............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `, mySprite3, 12, 12)
    projectile2 = sprites.createProjectileFromSprite(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........a...............
        ........aba..............
        ........aba..............
        .......aaba..............
        .......aaba..............
        .......abbaa.............
        ......aabfba.............
        ......abffba.............
        .....abfccfba............
        .....abfccfba............
        .....abfccfba............
        .....abffffba............
        ......abbbba.............
        .......aaaa..............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `, mySprite3, 0, 200)
    projectile2 = sprites.createProjectileFromSprite(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........a...............
        ........aba..............
        ........aba..............
        .......aaba..............
        .......aaba..............
        .......abbaa.............
        ......aabfba.............
        ......abffba.............
        .....abfccfba............
        .....abfccfba............
        .....abfccfba............
        .....abffffba............
        ......abbbba.............
        .......aaaa..............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `, mySprite3, 0, 200)
})
